# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Card": "00_core.ipynb"}

modules = ["core.py",
           "feature_eng.py",
           "training.py"]

doc_url = "https://fastai.github.io/deck_of_cards/"

git_url = "https://github.com/fastai/deck_of_cards/tree/master/"

def custom_doc_links(name): return None
